### ISSUE TITLE
Can't build app for x86_64 architecture

### ISSUE THREAD

**Issue by drronnie85** [talkkonnect/talkkonnect#59]
I successfully build talkkonnect for OrangePi
But when I run build on x86_64 I got error:

 go build -o /home/talkkonnect/bin/talkkonnect cmd/talkkonnect/main.go
In file included from ./opus-1.3.1/silk/SigProc_FIX.h:51,
                 from ./opus-1.3.1/silk/main.h:31,
                 from ./opus-1.3.1/silk/CNG.c:32,
                 from ../gopus/opus_nonshared.go:11:
./opus-1.3.1/silk/arm/biquad_alt_arm.h:31:11: fatal error: celt/arm/armcpu.h: No such file or directory
   31 | # include "celt/arm/armcpu.h"
      |           ^~~~~~~~~~~~~~~~~~~
compilation terminated.

How to fix it?

**Comment by talkkonnect** [comment]
Yes as zrdimetc said above you willl have to revert back to old version of gopus and also opus library to build on x86 arch. You can get the old versions from the repo https://github.com/layeh/barnard
Some work will be required to modify the code to get it to work with talkkonnect.

Since this is golang using cgo its not easy. However since the primary platform we chose is arm we chose to go the the latest version of opus and not be stuck with the old version.

**Comment by zrdimetc** [comment]
@drronnie85. Replace `config.h` in `opus-1.3.1` folder with version from the attached config.x86_64.zip file. Or just remove old `config.h` and run `./configure` from inside opus-1.3.1, it will recreate config headers for your platform. Without going into too many details, replace old `opus_nonshared.go` with version from the attached `opus_nonshared.zip` file. The needed changes will be committed later so these steps won't be necessary any more.
[config.x86_64.zip](https://github.com/talkkonnect/talkkonnect/files/8053148/config.x86_64.zip)
[opus_nonshared.zip](https://github.com/talkkonnect/talkkonnect/files/8053151/opus_nonshared.zip)
